version: '3'

volumes:
  pg_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ['bin/rails', 's', '-p', '3000', '-b', '0.0.0.0']
    depends_on:
      - db
    entrypoint: entrypoint.sh
    env_file:
      - .env.development
    environment:
      HISTFILE: /usr/src/app/log/.bash_history
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5444:5432"
    volumes:
      # Mount the DB dumps folder into the container, to be able to create & access database dumps:
      # - ./db/dumps:/db/dumps
      # Mount out tmp folder, we might want to have access to something there during development:
      #- ./tmp_db:/tmp
      # Mount our 'restoredb' script:
      # - ./bin/restoredb:/bin/restoredb:ro
      # Mount our 'dumpdb' script:
      # - ./bin/dumpdb:/bin/dumpdb:ro
      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
      - pg_data:/var/lib/postgresql/data
